"""create tables

Revision ID: 4abc3166b85d
Revises: 
Create Date: 2019-04-15 00:27:08.794383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abc3166b85d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('is_finish', sa.Boolean(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('follow', sa.String(length=20), nullable=True),
    sa.Column('play', sa.String(length=20), nullable=True),
    sa.Column('pub_date', sa.Integer(), nullable=True),
    sa.Column('pub_real_time', sa.Integer(), nullable=True),
    sa.Column('renewal_time', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animation_media_id'), 'animation', ['media_id'], unique=False)
    op.create_table('animation_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('tag_list', sa.Text(), nullable=True),
    sa.Column('review_times', sa.Integer(), nullable=True),
    sa.Column('character_voice_list', sa.Text(), nullable=True),
    sa.Column('character_staff_list', sa.Text(), nullable=True),
    sa.Column('short_comment_sum', sa.Integer(), nullable=True),
    sa.Column('long_comment_sum', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['animation.media_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animation_feature')
    op.drop_index(op.f('ix_animation_media_id'), table_name='animation')
    op.drop_table('animation')
    # ### end Alembic commands ###
