"""add table AnimationFeature

Revision ID: 5afe91f03514
Revises: 5ec991e02e17
Create Date: 2019-04-13 23:21:12.231067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afe91f03514'
down_revision = '5ec991e02e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'animation_feature', 'animation', ['media_id'], ['media_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animation_feature', type_='foreignkey')
    # ### end Alembic commands ###
