"""add table AnimationFeature

Revision ID: 5ec991e02e17
Revises: 500175e2908a
Create Date: 2019-04-13 23:20:52.454898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec991e02e17'
down_revision = '500175e2908a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('tag_list', sa.Text(), nullable=True),
    sa.Column('character_voice_list', sa.Text(), nullable=True),
    sa.Column('character_staff_list', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('animation', sa.Column('character_staff_list', sa.Text(), nullable=True))
    op.add_column('animation', sa.Column('character_voice_list', sa.Text(), nullable=True))
    op.add_column('animation', sa.Column('tag_list', sa.Text(), nullable=True))
    op.create_index(op.f('ix_animation_media_id'), 'animation', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animation_media_id'), table_name='animation')
    op.drop_column('animation', 'tag_list')
    op.drop_column('animation', 'character_voice_list')
    op.drop_column('animation', 'character_staff_list')
    op.drop_table('animation_feature')
    # ### end Alembic commands ###
