"""create tables

Revision ID: 90df321fec1c
Revises: c13dadd42b6f
Create Date: 2019-04-13 00:27:35.945680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90df321fec1c'
down_revision = 'c13dadd42b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
