"""delete tables

Revision ID: c13dadd42b6f
Revises: 6dc385799300
Create Date: 2019-04-13 00:27:12.084256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c13dadd42b6f'
down_revision = '6dc385799300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('link', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_finish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('media_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('follow', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('play', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pub_date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pub_real_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('renewal_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('season_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
