"""create table animation

Revision ID: d67c7e94f782
Revises: 
Create Date: 2019-04-10 22:53:33.229151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67c7e94f782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('is_finish', sa.Boolean(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('follow', sa.String(length=20), nullable=True),
    sa.Column('play', sa.String(length=20), nullable=True),
    sa.Column('pub_date', sa.Integer(), nullable=True),
    sa.Column('pub_real_time', sa.Integer(), nullable=True),
    sa.Column('renewal_time', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animation')
    # ### end Alembic commands ###
