"""add userinfo, userupstat, userstat tables

Revision ID: dce2c38cf195
Revises: 4abc3166b85d
Create Date: 2019-04-17 21:38:19.635423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce2c38cf195'
down_revision = '4abc3166b85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('sign', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('jointime', sa.Integer(), nullable=True),
    sa.Column('moral', sa.Integer(), nullable=True),
    sa.Column('silence', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('fans_badge', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('vip_type', sa.Integer(), nullable=True),
    sa.Column('vip_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_mid'), 'user_info', ['mid'], unique=False)
    op.create_table('user_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('whisper', sa.Integer(), nullable=True),
    sa.Column('black', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['user_info.mid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_upstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('archive_view', sa.Integer(), nullable=True),
    sa.Column('article_view', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['user_info.mid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_upstat')
    op.drop_table('user_stat')
    op.drop_index(op.f('ix_user_info_mid'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
