"""create tables

Revision ID: f175e0764acf
Revises: 90df321fec1c
Create Date: 2019-04-13 00:28:04.998393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f175e0764acf'
down_revision = '90df321fec1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
